import { NormalizedTransaction } from '../types';

export const COLUMN_ALIASES: Record<keyof NormalizedTransaction, string[]> = {
    symbol: ['symbol', 'ticker', 'stock', 'stock name', 'instrument', 'name', 'security'],
    side: ['side', 'action', 'b/s', 'buy/sell', 'type', 'direction', 'trade type', 'transaction type', 'trans code'],
    date: ['date', 'trade date', 'execution date', 'create date', 'create date & time', 'datetime', 'time', 'run date', 'activity date', 'transaction date'],
    quantity: ['quantity', 'qty', 'shares', 'volume', 'size', 'order quantity', 'confirmed quantity', 'lots', 'filled qty'],
    price: ['price', 'executed price', 'exec price', 'avg price', 'fill price', 'average price', 'trade price'],
    time: ['time', 'execution time', 'trade time'],
    tradeDate: ['tradedate', 'trade date', 'settlement date'],
    accountId: ['account id', 'account', 'client account id', 'clientaccountid'],
    orderId: ['order id', 'trade id', 'id', 'ref', 'reference', 'order no'],
    assetClass: ['asset class', 'asset category', 'security type'],
    multiplier: ['multiplier', 'contract multiplier'],
    companyName: ['company', 'company name', 'stock name', 'name', 'description'],
    currency: ['currency', 'ccy', 'cur'],
    exchanges: ['exchange', 'exchanges', 'market', 'venue'],
    orderType: ['order type', 'type', 'order kind'],
    commission: ['commission', 'fee', 'fees', 'brokerage', 'fees & comm', 'fees & commission'],
    stockCode: ['stock code', 'code', 'isin', 'sedol'],
    totalValue: ['total', 'total value', 'amount', 'value', 'net amount', 'consideration', 'total amount'],
    realizedPnL: ['realized pnl', 'pnl', 'profit', 'gain/loss', 'realised p&l', 'realized profit'],
    unrealizedPnL: ['unrealized pnl', 'unrealized profit', 'mark to market', 'unrealised p&l'],
    fxRateToBase: ['fxratetobase', 'fx rate to base', 'fx rate'],
    openClose: ['open/closeindicator', 'opencloseindicator', 'open/close', 'openclose'],
};
